image: ubuntu:bionic

variables:
  DEPENDENCIES: "331"

stages:
  - test
  - build

before_script:
  - echo "Before script installation"
  - apt update
  - apt install libdevel-cover-perl libtap-formatter-junit-perl libjson-xs-perl libtest-most-perl libtest-mockmodule-perl cpanminus make curl unzip -y
  - echo "Installing DEPENDENCY OpenTracing::Interface"
  - curl --location --output artifacts.zip 'https://git.perceptyx.com/api/v4/projects/331/jobs/artifacts/master/download?job=package'
  - unzip artifacts.tar.gz
  - tar xzvf OpenTracing-Interface-0.02.tar.gz
  - cd OpenTracing-Interface-0.02
  - perl Makefile.PL
  - make install
  - cd -

test:unit:
  stage: test
  script:
    - prove -MDevel::Cover -l lib -r t/
  coverage: /Totals+.+s(d+.d+?)$/

package:
  stage: build
  script:
    - cpanm --installdeps .
    - perl Makefile.PL
    - make dist
  artifacts:
    paths:
    - "*.tar.gz"
    expire_in: 1 week
